targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: graphql_comparison|lib/graphql/schema.graphql
          output_dir: "../lib"
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: graphql_comparison|lib/graphql/schema.graphql
          output_dir: "../lib"
