name: graphql_comparison
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0-85.0.dev <4.0.0"

# Add regular dependencies here.
dependencies:
  ferry: 0.13.0
  gql_http_link: ^0.4.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: 2.3.3
  ferry_generator: 0.7.0
