name: artemis_comparison
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0-85.0.dev <4.0.0"

dev_dependencies:
  artemis: ">=7.0.0 <8.0.0"
  build_runner: ^2.1.4
  json_serializable: ^6.0.1
